spring:
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Seoul
    username: root
    password: 20375570
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  elasticsearch:
    uris: http://localhost:9200

jwt:
  secret:
    access: "5/QWm//BsCVJ41ORLonFufODCm9NWn0zsGK8/Wff+Lo="
    refresh: "0ZFrg+SUY41noBVrteelT1EuHJChth7S0dbykMWSYFM="
  expiration:
    access: 3600000  # 1??
    refresh: 604800000  # 7?

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: INFO
    com.devita: DEBUG
    org.springframework.security: DEBUG


springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(??? ????), method(HTTP????)
    tags-sorter: alpha # ?? ?? ??
    path: /api-docs # html ?? ?? ??
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none # tag, operation ??? ??

front:
  redirectUrl: "http://localhost:3000/redirect"

cors:
  allowed-origins: "http://localhost:3000"

ai:
  address: "http://localhost:8000"

management:
  endpoints:
    web:
      exposure:
        include: "*"